2021-01-15T16:45:25.018080500Z Traceback (most recent call last):
2021-01-15T16:45:25.018168500Z   File "/tmp/entrypoint.py", line 82, in <module>
2021-01-15T16:45:25.018207800Z     main()
2021-01-15T16:45:25.018243800Z   File "/tmp/entrypoint.py", line 77, in main
2021-01-15T16:45:25.018280000Z     raise FileNotFoundError("/workspace/" + options.script)
2021-01-15T16:45:25.018316500Z FileNotFoundError: /workspace/analysis/11b_eth_an_infectedpop_eth16_nocarehomes.do


state: failed
commit: none
docker_image_id: sha256:e4a676ff497b1550742032051cce1ba5502f65b172e86e4d82aadbaa1e056935
job_id: jpeggdbxznrjaxcr
run_by_user: None
created_at: 2021-01-15T16:43:35Z
started_at: 2021-01-15T16:45:24Z
completed_at: 2021-01-15T16:45:27Z

Job exited with an error code

outputs:
  (no outputs)